/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smpractica4_P12;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Transparency;
import java.awt.color.ColorSpace;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BandCombineOp;
import java.awt.image.BufferedImage;
import java.awt.image.ByteLookupTable;
import java.awt.image.ColorConvertOp;
import java.awt.image.ColorModel;
import java.awt.image.ComponentColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.DataBuffer;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.event.InternalFrameAdapter;
import sm.acz.imagen.OscurecerOp;
import sm.acz.imagen.PosterizarOp;
import sm.acz.imagen.RojoOp;
import sm.acz.imagen.TonoColorOp;
import sm.acz.iu.Herramientas_dibujo;
import sm.acz.iu.Lienzo2D;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;
import sm.image.SepiaOp;
import sm.image.TintOp;
import sm.iu.DialogoFuncionABC;



/**
 *
 * @author alejandro
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private BufferedImage imgFuente = null;
    BufferedImage imgCopia = null;  
    DialogoFuncionABC dlgFuncion = null;
    private boolean oscuro_invertido = false;
    
   
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(900,900);
        boton_Linea.setSelected(true);
    }
    
    private Lienzo2D getSelectedLienzo() {
        VentanaInterna vi;
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        return vi!=null ? vi.getLienzo2D() : null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        boton_nuevo = new javax.swing.JButton();
        boton_abrir = new javax.swing.JButton();
        boton_guardar = new javax.swing.JButton();
        boton_Linea = new javax.swing.JToggleButton();
        boton_Rectangulo = new javax.swing.JToggleButton();
        boton_Elipse = new javax.swing.JToggleButton();
        boton_curva = new javax.swing.JToggleButton();
        boton_editar = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        boton_color = new javax.swing.JButton();
        boton_relleno = new javax.swing.JToggleButton();
        boton_transparencia = new javax.swing.JToggleButton();
        boton_alisado = new javax.swing.JToggleButton();
        boton_fijar = new javax.swing.JToggleButton();
        boton_eliminar = new javax.swing.JToggleButton();
        deslizador_grosor = new javax.swing.JSlider();
        boton_negativo = new javax.swing.JToggleButton();
        boton_duplicar = new javax.swing.JButton();
        boton_realceOscuros = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deslizador_iluminacion = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        deslizador_contraste = new javax.swing.JSlider();
        menu_convolveOp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        deslizador_emborronamiento = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        deslizador_perfilado = new javax.swing.JSlider();
        boton_contraste1 = new javax.swing.JButton();
        boton_oscurecer = new javax.swing.JButton();
        boton_aclarar = new javax.swing.JButton();
        boton_deslizadores = new javax.swing.JToggleButton();
        deslizador_a = new javax.swing.JSlider();
        deslizador_b = new javax.swing.JSlider();
        deslizador_c = new javax.swing.JSlider();
        boton_invertirocuro = new javax.swing.JButton();
        boton_girar180 = new javax.swing.JButton();
        boton_mas = new javax.swing.JButton();
        boton_menos = new javax.swing.JButton();
        boton_showBandas = new javax.swing.JButton();
        seleccionEspaciosColor = new javax.swing.JComboBox<>();
        boton_bandCombineOp = new javax.swing.JButton();
        boton_tintado = new javax.swing.JButton();
        deslizador_tintado = new javax.swing.JSlider();
        boton_sepia = new javax.swing.JButton();
        boton_filtrorojo = new javax.swing.JButton();
        deslizador_rojo = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        deslizador_posterizacion = new javax.swing.JSlider();
        boton_tonocolor = new javax.swing.JToggleButton();
        deslizador_desplazamiento = new javax.swing.JSlider();
        deslizador_umbral = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        deslizador_oscurecer = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu_audio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        RescaleOp = new javax.swing.JMenuItem();
        ConvolveOp = new javax.swing.JMenuItem();
        BandCombineOp = new javax.swing.JMenuItem();
        ColorConvertOp = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        boton_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/nuevo.png"))); // NOI18N
        boton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevoActionPerformed(evt);
            }
        });
        jPanel4.add(boton_nuevo);

        boton_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/abrir.png"))); // NOI18N
        boton_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_abrirActionPerformed(evt);
            }
        });
        jPanel4.add(boton_abrir);

        boton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/guardar.png"))); // NOI18N
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });
        jPanel4.add(boton_guardar);

        buttonGroup1.add(boton_Linea);
        boton_Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/linea.png"))); // NOI18N
        boton_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_LineaActionPerformed(evt);
            }
        });
        jPanel4.add(boton_Linea);

        buttonGroup1.add(boton_Rectangulo);
        boton_Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/rectangulo.png"))); // NOI18N
        boton_Rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RectanguloActionPerformed(evt);
            }
        });
        jPanel4.add(boton_Rectangulo);

        buttonGroup1.add(boton_Elipse);
        boton_Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/elipse.png"))); // NOI18N
        boton_Elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ElipseActionPerformed(evt);
            }
        });
        jPanel4.add(boton_Elipse);

        buttonGroup1.add(boton_curva);
        boton_curva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/curva.png"))); // NOI18N
        boton_curva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_curvaActionPerformed(evt);
            }
        });
        jPanel4.add(boton_curva);

        buttonGroup1.add(boton_editar);
        boton_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/seleccion.png"))); // NOI18N
        boton_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_editarActionPerformed(evt);
            }
        });
        jPanel4.add(boton_editar);

        jPanel6.setMaximumSize(new java.awt.Dimension(30, 30));
        jPanel6.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel6.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.setLayout(new java.awt.BorderLayout());

        boton_color.setBackground(new java.awt.Color(0, 0, 0));
        boton_color.setBorder(null);
        boton_color.setMargin(null);
        boton_color.setOpaque(true);
        boton_color.setPreferredSize(new java.awt.Dimension(30, 30));
        boton_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_colorActionPerformed(evt);
            }
        });
        jPanel6.add(boton_color, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        boton_relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/rellenar.png"))); // NOI18N
        boton_relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_rellenoActionPerformed(evt);
            }
        });
        jPanel4.add(boton_relleno);

        boton_transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/transparencia.png"))); // NOI18N
        boton_transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_transparenciaActionPerformed(evt);
            }
        });
        jPanel4.add(boton_transparencia);

        boton_alisado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/alisar.png"))); // NOI18N
        boton_alisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_alisadoActionPerformed(evt);
            }
        });
        jPanel4.add(boton_alisado);

        buttonGroup1.add(boton_fijar);
        boton_fijar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/fijar.png"))); // NOI18N
        boton_fijar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_fijarActionPerformed(evt);
            }
        });
        jPanel4.add(boton_fijar);

        buttonGroup1.add(boton_eliminar);
        boton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/eliminar.png"))); // NOI18N
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(boton_eliminar);

        deslizador_grosor.setMaximum(10);
        deslizador_grosor.setMinimum(1);
        deslizador_grosor.setValue(1);
        deslizador_grosor.setPreferredSize(new java.awt.Dimension(100, 20));
        deslizador_grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_grosorStateChanged(evt);
            }
        });
        deslizador_grosor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                deslizador_grosorMouseDragged(evt);
            }
        });
        jPanel4.add(deslizador_grosor);

        boton_negativo.setText("Negativo");
        boton_negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_negativoActionPerformed(evt);
            }
        });
        jPanel4.add(boton_negativo);

        boton_duplicar.setText("Duplicar");
        boton_duplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_duplicarActionPerformed(evt);
            }
        });
        jPanel4.add(boton_duplicar);

        boton_realceOscuros.setText("Oscuros");
        boton_realceOscuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_realceOscurosActionPerformed(evt);
            }
        });
        jPanel4.add(boton_realceOscuros);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        estado.setText("Línea");
        jPanel2.add(estado, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/brillo.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(12, 12));
        jPanel5.add(jLabel1);

        deslizador_iluminacion.setMaximum(255);
        deslizador_iluminacion.setMinimum(-255);
        deslizador_iluminacion.setToolTipText("");
        deslizador_iluminacion.setValue(0);
        deslizador_iluminacion.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_iluminacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_iluminacionStateChanged(evt);
            }
        });
        deslizador_iluminacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_iluminacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_iluminacionFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_iluminacion);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/contraste.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(12, 12));
        jPanel5.add(jLabel2);

        deslizador_contraste.setMaximum(20);
        deslizador_contraste.setMinimum(1);
        deslizador_contraste.setValue(10);
        deslizador_contraste.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_contraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_contrasteStateChanged(evt);
            }
        });
        deslizador_contraste.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_contrasteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_contrasteFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_contraste);

        menu_convolveOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Binomial", "Enfoque", "Relieve", "Laplaciano" }));
        menu_convolveOp.setPreferredSize(new java.awt.Dimension(50, 20));
        menu_convolveOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_convolveOpActionPerformed(evt);
            }
        });
        jPanel5.add(menu_convolveOp);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/emborronar.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(12, 12));
        jPanel5.add(jLabel3);

        deslizador_emborronamiento.setMaximum(31);
        deslizador_emborronamiento.setMinimum(1);
        deslizador_emborronamiento.setValue(1);
        deslizador_emborronamiento.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_emborronamiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_emborronamientoStateChanged(evt);
            }
        });
        deslizador_emborronamiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_emborronamientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_emborronamientoFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_emborronamiento);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/perfilar.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(12, 12));
        jPanel5.add(jLabel4);

        deslizador_perfilado.setMaximum(15);
        deslizador_perfilado.setMinimum(1);
        deslizador_perfilado.setValue(1);
        deslizador_perfilado.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_perfilado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_perfiladoStateChanged(evt);
            }
        });
        deslizador_perfilado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_perfiladoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_perfiladoFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_perfilado);

        boton_contraste1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/contraste_1.png"))); // NOI18N
        boton_contraste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_contraste1ActionPerformed(evt);
            }
        });
        jPanel5.add(boton_contraste1);

        boton_oscurecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/ocurecer.png"))); // NOI18N
        boton_oscurecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_oscurecerActionPerformed(evt);
            }
        });
        jPanel5.add(boton_oscurecer);

        boton_aclarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/iluminar.png"))); // NOI18N
        boton_aclarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aclararActionPerformed(evt);
            }
        });
        jPanel5.add(boton_aclarar);

        boton_deslizadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/operador2.png"))); // NOI18N
        boton_deslizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_deslizadoresActionPerformed(evt);
            }
        });
        jPanel5.add(boton_deslizadores);

        deslizador_a.setMaximum(255);
        deslizador_a.setValue(0);
        deslizador_a.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_a.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_aStateChanged(evt);
            }
        });
        jPanel5.add(deslizador_a);

        deslizador_b.setMaximum(255);
        deslizador_b.setValue(128);
        deslizador_b.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_b.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_bStateChanged(evt);
            }
        });
        jPanel5.add(deslizador_b);

        deslizador_c.setMaximum(256);
        deslizador_c.setValue(255);
        deslizador_c.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_c.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_cStateChanged(evt);
            }
        });
        jPanel5.add(deslizador_c);

        boton_invertirocuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/operador1.png"))); // NOI18N
        boton_invertirocuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_invertirocuroActionPerformed(evt);
            }
        });
        jPanel5.add(boton_invertirocuro);

        boton_girar180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/rotar180.png"))); // NOI18N
        boton_girar180.setToolTipText("");
        boton_girar180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_girar180ActionPerformed(evt);
            }
        });
        jPanel5.add(boton_girar180);

        boton_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/mas.png"))); // NOI18N
        boton_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_masActionPerformed(evt);
            }
        });
        jPanel5.add(boton_mas);

        boton_menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/menos.png"))); // NOI18N
        boton_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_menosActionPerformed(evt);
            }
        });
        jPanel5.add(boton_menos);

        boton_showBandas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/bandas.png"))); // NOI18N
        boton_showBandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_showBandasActionPerformed(evt);
            }
        });
        jPanel5.add(boton_showBandas);

        seleccionEspaciosColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RGB", "YCC", "GREY" }));
        seleccionEspaciosColor.setPreferredSize(new java.awt.Dimension(50, 20));
        seleccionEspaciosColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionEspaciosColorActionPerformed(evt);
            }
        });
        jPanel5.add(seleccionEspaciosColor);

        boton_bandCombineOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/combinar.png"))); // NOI18N
        boton_bandCombineOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bandCombineOpActionPerformed(evt);
            }
        });
        jPanel5.add(boton_bandCombineOp);

        boton_tintado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/tintar.png"))); // NOI18N
        boton_tintado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tintadoActionPerformed(evt);
            }
        });
        jPanel5.add(boton_tintado);

        deslizador_tintado.setValue(0);
        deslizador_tintado.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_tintado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_tintadoStateChanged(evt);
            }
        });
        deslizador_tintado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_tintadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_tintadoFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_tintado);

        boton_sepia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/sepia.png"))); // NOI18N
        boton_sepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sepiaActionPerformed(evt);
            }
        });
        jPanel5.add(boton_sepia);

        boton_filtrorojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/rojo.png"))); // NOI18N
        boton_filtrorojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_filtrorojoActionPerformed(evt);
            }
        });
        jPanel5.add(boton_filtrorojo);

        deslizador_rojo.setMaximum(255);
        deslizador_rojo.setMinimum(2);
        deslizador_rojo.setValue(3);
        deslizador_rojo.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_rojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_rojoStateChanged(evt);
            }
        });
        deslizador_rojo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_rojoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_rojoFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_rojo);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/posterizar.png"))); // NOI18N
        jPanel5.add(jLabel5);

        deslizador_posterizacion.setMaximum(20);
        deslizador_posterizacion.setMinimum(2);
        deslizador_posterizacion.setValue(10);
        deslizador_posterizacion.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_posterizacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_posterizacionStateChanged(evt);
            }
        });
        deslizador_posterizacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_posterizacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_posterizacionFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_posterizacion);

        boton_tonocolor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/paleta.png"))); // NOI18N
        boton_tonocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tonocolorActionPerformed(evt);
            }
        });
        jPanel5.add(boton_tonocolor);

        deslizador_desplazamiento.setMaximum(360);
        deslizador_desplazamiento.setValue(180);
        deslizador_desplazamiento.setPreferredSize(new java.awt.Dimension(50, 20));
        deslizador_desplazamiento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_desplazamientoStateChanged(evt);
            }
        });
        deslizador_desplazamiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_desplazamientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_desplazamientoFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_desplazamiento);

        deslizador_umbral.setMaximum(360);
        deslizador_umbral.setToolTipText("");
        deslizador_umbral.setValue(180);
        deslizador_umbral.setPreferredSize(new java.awt.Dimension(50, 20));
        deslizador_umbral.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_umbralStateChanged(evt);
            }
        });
        jPanel5.add(deslizador_umbral);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Iconos-20250310/persona (1).png"))); // NOI18N
        jPanel5.add(jLabel6);

        deslizador_oscurecer.setValue(100);
        deslizador_oscurecer.setPreferredSize(new java.awt.Dimension(40, 20));
        deslizador_oscurecer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizador_oscurecerStateChanged(evt);
            }
        });
        deslizador_oscurecer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deslizador_oscurecerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deslizador_oscurecerFocusLost(evt);
            }
        });
        jPanel5.add(deslizador_oscurecer);

        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_START);
        jPanel3.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1341, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menu_audio.setText("Abrir Audio");
        menu_audio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_audioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_audio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagen");

        RescaleOp.setText("Operador RescaleOp");
        RescaleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RescaleOpActionPerformed(evt);
            }
        });
        jMenu2.add(RescaleOp);

        ConvolveOp.setText("Operador ConvolveOp");
        ConvolveOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvolveOpActionPerformed(evt);
            }
        });
        jMenu2.add(ConvolveOp);

        BandCombineOp.setText("Operador BandCombineOp");
        BandCombineOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandCombineOpActionPerformed(evt);
            }
        });
        jMenu2.add(BandCombineOp);

        ColorConvertOp.setText("Operador ColorConvertOp");
        ColorConvertOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorConvertOpActionPerformed(evt);
            }
        });
        jMenu2.add(ColorConvertOp);

        jMenuItem5.setText("Operador AffineTransformOp");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Operador LookupOp");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class ManejadorVentanaInterna extends InternalFrameAdapter{
        @Override
        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                System.out.println("internalFrameActivated called for frame: " + evt.getInternalFrame().getTitle());

            VentanaInterna vi = (VentanaInterna) evt.getInternalFrame();
            Lienzo2D lienzo2D1 = vi.getLienzo2D();

            boton_relleno.setSelected(lienzo2D1.isRelleno());
            boton_editar.setSelected(lienzo2D1.isEditar());
            boton_alisado.setSelected(lienzo2D1.isAlisar());
            boton_transparencia.setSelected(lienzo2D1.isTransparencia());
            boton_eliminar.setSelected(lienzo2D1.isEliminar());
            boton_fijar.setSelected(lienzo2D1.isFijar());
            boton_color.setBackground(lienzo2D1.getColor());
            deslizador_grosor.setValue(lienzo2D1.getGrosor());
            
            // Deseleccionamos todos los botones de figura
            boton_Linea.setSelected(false);
            boton_Rectangulo.setSelected(false);
            boton_Elipse.setSelected(false);
            boton_curva.setSelected(false);

            // Seleccionamos el botón correspondiente a la figura activa
            switch (lienzo2D1.getFigura_select()) {
                case LINEA:
                    boton_Linea.setSelected(true);
                    break;
                case RECTANGULO:
                    boton_Rectangulo.setSelected(true);
                    break;
                case ELIPSE:
                    boton_Elipse.setSelected(true);
                    break;
                case CURVA:
                    boton_curva.setSelected(true);
                    break;
            }
           

        }
        
        
        

    }
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        nuevo();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void boton_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_LineaActionPerformed
        // TODO add your handling code here:
        //lienzo.getForma();
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        estado.setText("Línea");
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setFigura_select(Herramientas_dibujo.LINEA);
        }
        
        
    }//GEN-LAST:event_boton_LineaActionPerformed

    private void boton_RectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RectanguloActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        estado.setText("Rectángulo");
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setFigura_select(Herramientas_dibujo.RECTANGULO);
        }
        
    }//GEN-LAST:event_boton_RectanguloActionPerformed

    private void boton_ElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ElipseActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        estado.setText("Elipse");
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setFigura_select(Herramientas_dibujo.ELIPSE);
        }
    }//GEN-LAST:event_boton_ElipseActionPerformed

    private void boton_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_editarActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
           lienzo2D1.reestablecer(); 
           lienzo2D1.setEditar(true);     
        }
    }//GEN-LAST:event_boton_editarActionPerformed

    private void deslizador_grosorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deslizador_grosorMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deslizador_grosorMouseDragged

    private void deslizador_grosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_grosorStateChanged
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null)
        lienzo2D1.setGrosor(deslizador_grosor.getValue());
        if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
            lienzo2D1.getForma().setTrazo(deslizador_grosor.getValue());
            
             VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
             if (vi != null) {
                 vi.getLienzo2D().repaint();
             }
            
        }
        
    }//GEN-LAST:event_deslizador_grosorStateChanged

    private void boton_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_colorActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            Color color = JColorChooser.showDialog(this, "Elije un color", Color.RED);
            boton_color.setBackground(color);
            lienzo2D1.setColor(color);
            if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
                lienzo2D1.getForma().setColor(color);
                VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
                if (vi != null) {
                    vi.getLienzo2D().repaint();
                }
            }
        }
        
        
    }//GEN-LAST:event_boton_colorActionPerformed

    private void boton_curvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_curvaActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        estado.setText("Curva");
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setFigura_select(Herramientas_dibujo.CURVA);
            lienzo2D1.setEditar(false);
        }
    }//GEN-LAST:event_boton_curvaActionPerformed

    //IMPORTANTE PREGUNTA EXAMEN
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        abrir();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getPaintedImage();
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                    System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }     
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void boton_rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_rellenoActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            if(boton_relleno.isSelected()==true){
                lienzo2D1.setRelleno(true);
                if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
                    lienzo2D1.getForma().setRelleno(true);
                }
            }
            else{
                lienzo2D1.setRelleno(false);
                if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
                    lienzo2D1.getForma().setRelleno(false);
                }
            }
            VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null) {
                vi.getLienzo2D().repaint();
            }
        }
    }//GEN-LAST:event_boton_rellenoActionPerformed

    private void boton_transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_transparenciaActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            if(boton_transparencia.isSelected()==true){
                lienzo2D1.setTransparencia(true);
                if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
                   lienzo2D1.getForma().setTransparencia(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
                }
            }
            else{
                lienzo2D1.setTransparencia(false);
                if(lienzo2D1.getForma()!=null && lienzo2D1.isEditar()){
                   lienzo2D1.getForma().setTransparencia(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 1.0f));
                }
            }
            VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null) {
                vi.getLienzo2D().repaint();
            }
        }
    }//GEN-LAST:event_boton_transparenciaActionPerformed

    private void boton_alisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_alisadoActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            if (boton_alisado.isSelected() == true) {
                lienzo2D1.setAlisar(true);
                if (lienzo2D1.getForma() != null && lienzo2D1.isEditar()) {
                    lienzo2D1.getForma().setAlisado(new RenderingHints(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON));
                }
            } else {
                lienzo2D1.setAlisar(false);
                if (lienzo2D1.getForma() != null && lienzo2D1.isEditar()) {
                    lienzo2D1.getForma().setAlisado(new RenderingHints(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF));
                }
            }
            VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null) {
                vi.getLienzo2D().repaint();
            }
        }
    }//GEN-LAST:event_boton_alisadoActionPerformed

    private void boton_fijarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_fijarActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setFijar(true);
            
            estado.setText("Fijar");
        }
    }//GEN-LAST:event_boton_fijarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if(lienzo2D1!=null){
            lienzo2D1.reestablecer();
            lienzo2D1.setEliminar(true);
            estado.setText("Eliminar");
        }
    }//GEN-LAST:event_boton_eliminarActionPerformed

    private void RescaleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescaleOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if(img!=null){
                try{
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    rop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_RescaleOpActionPerformed

    private void ConvolveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvolveOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if(img!=null){
                try{
                    float filtro[] = {0.1f, 0.1f, 0.1f, 0.1f, 0.2f, 0.1f,0.1f, 0.1f, 0.1f};
                    Kernel k = new Kernel(3, 3, filtro);
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ConvolveOpActionPerformed

    private void deslizador_iluminacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_iluminacionStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if(img!=null){
                try{
                    int brillo = this.deslizador_iluminacion.getValue();
                    RescaleOp rop = new RescaleOp(1.0F, brillo,  null);
                    rop.filter(imgFuente, img);
                    escritorio  .repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        
    }//GEN-LAST:event_deslizador_iluminacionStateChanged

    private void deslizador_iluminacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_iluminacionFocusGained
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgFuente = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_iluminacionFocusGained

    private void deslizador_iluminacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_iluminacionFocusLost
        imgFuente = null;
        
        this.deslizador_iluminacion.setValue(0);
    }//GEN-LAST:event_deslizador_iluminacionFocusLost

    private void menu_convolveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_convolveOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            
            Kernel k = getKernel(this.menu_convolveOp.getSelectedIndex());
            
            if(img!=null && k!=null){
                try{
                    
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menu_convolveOpActionPerformed

    private void deslizador_contrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_contrasteStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if(img!=null){
                try{
                    float contraste = this.deslizador_contraste.getValue();
                    contraste/=10;
                    RescaleOp rop = new RescaleOp(contraste, 0.0F,  null);
                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_deslizador_contrasteStateChanged

    private void deslizador_contrasteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_contrasteFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgFuente = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_contrasteFocusGained

    private void deslizador_contrasteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_contrasteFocusLost
        // TODO add your handling code here:
        imgFuente = null;
        
        this.deslizador_contraste.setValue(0);
    }//GEN-LAST:event_deslizador_contrasteFocusLost

    private void deslizador_emborronamientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_emborronamientoStateChanged
        // TODO add your handling code here:
        
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null ) {

            int size = this.deslizador_emborronamiento.getValue();

            if (size % 2 == 0){
               size += 1;
            } 
             
            float[] filtro = new float [size*size];
            float value = 1.0F/(size*size);
            
            for (int i = 0; i < filtro.length; i++) {
                filtro[i] = value;
            }
            
            Kernel k = new Kernel(size, size, filtro);
            
            
                try{
                    
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgdest = cop.filter(imgFuente, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch(IllegalArgumentException e){
                    System.err.println(e.getLocalizedMessage());
                }
            
        }
    }//GEN-LAST:event_deslizador_emborronamientoStateChanged

    private void deslizador_emborronamientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_emborronamientoFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgFuente = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_emborronamientoFocusGained

    private void deslizador_emborronamientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_emborronamientoFocusLost
        // TODO add your handling code here:
        imgFuente = null;
        
        this.deslizador_emborronamiento.setValue(1);
    }//GEN-LAST:event_deslizador_emborronamientoFocusLost

    private void deslizador_perfiladoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_perfiladoStateChanged
        // TODO add your handling code here:
         VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgFuente != null ) {

            int size = 3;
            
            float a = this.deslizador_perfilado.getValue();
            
            if(a<1){
                a = 1;
            }
            
            float[] filtro = new float [size*size];
            
            for(int i=0; i<filtro.length;i++){
                filtro[i]=0;
                if(i%2!=0){
                    filtro[i]=-a;
                }
                if(i==4){
                    filtro[i]=4*a+1;
                }
            }
            
            Kernel k = new Kernel(size, size, filtro);
          
            try {
                ConvolveOp cop = new ConvolveOp(k);
                BufferedImage imgdest = cop.filter(imgFuente, null);
                vi.getLienzo2D().setImage(imgdest);
                vi.getLienzo2D().repaint();
            } catch (IllegalArgumentException e) {
                System.err.println(e.getLocalizedMessage());
            }
            
        }
                          
        
    }//GEN-LAST:event_deslizador_perfiladoStateChanged

    private void deslizador_perfiladoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_perfiladoFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgFuente = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_perfiladoFocusGained

    private void deslizador_perfiladoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_perfiladoFocusLost
        // TODO add your handling code here:
        imgFuente = null;
        
        this.deslizador_perfilado.setValue(1);
    }//GEN-LAST:event_deslizador_perfiladoFocusLost

    private void boton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_boton_nuevoActionPerformed

    private void boton_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_abrirActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_boton_abrirActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi=(VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getPaintedImage();
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();
                        ImageIO.write(img, "jpg", f);
                        vi.setTitle(f.getName());
                    } catch (Exception ex) {
                    System.err.println("Error al guardar la imagen");
                    }
                }
            }
        }    
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void BandCombineOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandCombineOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                try {
                 
                    float[][] matriz = {{1.0F, 0.0F, 0.0F},
                                        {0.0F, 0.0F, 1.0F},
                                        {0.0F, 1.0F, 0.0F}};  
                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_BandCombineOpActionPerformed

    private void ColorConvertOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorConvertOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                try {
                    ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                    ColorConvertOp op = new ColorConvertOp(cs, null);
                    BufferedImage imgdest = op.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_ColorConvertOpActionPerformed

    private void boton_showBandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_showBandasActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                
                for(int i=0; i<img.getRaster().getNumBands(); i++){
                    BufferedImage imgbanda = getImageBand(img,i);
                    vi = new VentanaInterna();
                    vi.getLienzo2D().setImage(imgbanda);
                    escritorio.add(vi);
                    vi.setVisible(true);
                }
                
            }
            
        }
        
    }//GEN-LAST:event_boton_showBandasActionPerformed

    private void boton_bandCombineOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bandCombineOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                try {
                    float[][] matriz = {
                        {0.0f, 0.5f, 0.5f}, 
                        {0.5f, 0.0f, 0.5f}, 
                        {0.5f, 0.5f, 0.0f} 
                    };

                    BandCombineOp bcop = new BandCombineOp(matriz, null);
                    bcop.filter(img.getRaster(), img.getRaster());
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_boton_bandCombineOpActionPerformed

    private void seleccionEspaciosColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionEspaciosColorActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                int seleccion = this.seleccionEspaciosColor.getSelectedIndex();
                ColorSpace cs = null ;
                
                switch(seleccion){
                    case 0:
                         cs = ColorSpace.getInstance(ColorSpace.CS_sRGB);
                    break;
                    case 1:
                         cs = ColorSpace.getInstance(ColorSpace.CS_PYCC);
                    break;
                    case 2:
                         cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
                }
                
                try {
                    
                    ColorConvertOp op = new ColorConvertOp(cs, null);
                    BufferedImage imgdest = op.filter(img, null);
                    vi = new VentanaInterna();
                    vi.getLienzo2D().setImage(imgdest);
                    escritorio.add(vi);
                    vi.setVisible(true);
                    
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_seleccionEspaciosColorActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AffineTransform at = AffineTransform.getScaleInstance(1.5, 1.5);
        aplicarAffineTransform(at);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        byte funcionT[] = new byte[256];
        for (int x = 0; x < 256; x++) {
            funcionT[x] = (byte) (255 - x); // Negativo
        }
        LookupTable tabla = new ByteLookupTable(0, funcionT);
        aplicarLookup(tabla);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void boton_contraste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_contraste1ActionPerformed
        
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_SFUNCION);
            aplicarLookup(tabla);
        }
    }//GEN-LAST:event_boton_contraste1ActionPerformed

    private void boton_oscurecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_oscurecerActionPerformed
        
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_POWER);
            aplicarLookup(tabla);
        }
        
    }//GEN-LAST:event_boton_oscurecerActionPerformed

    private void boton_aclararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aclararActionPerformed
        
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_LOGARITHM);
            aplicarLookup(tabla);
        }
    }//GEN-LAST:event_boton_aclararActionPerformed

    private void boton_girar180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_girar180ActionPerformed

        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getRotateInstance(Math.toRadians(180), img.getWidth() / 2, img.getHeight() / 2);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        
    }//GEN-LAST:event_boton_girar180ActionPerformed

    private void boton_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_masActionPerformed
        // TODO add your handling code here:
        AffineTransform at = AffineTransform.getScaleInstance(1.25, 1.25);
        aplicarAffineTransform(at);
    }//GEN-LAST:event_boton_masActionPerformed

    private void boton_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_menosActionPerformed
        AffineTransform at = AffineTransform.getScaleInstance(0.75, 0.75);
        aplicarAffineTransform(at);
    }//GEN-LAST:event_boton_menosActionPerformed

    private void boton_deslizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_deslizadoresActionPerformed
        // TODO add your handling code here:
        if(dlgFuncion==null){
             dlgFuncion = new DialogoFuncionABC(this);
        }
        if(boton_deslizadores.isSelected()){
            VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
            if (vi != null) {
                imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            }
            dlgFuncion.setABC(deslizador_a.getValue(), deslizador_b.getValue(), deslizador_c.getValue()); //a, b y c los valores del slider
            dlgFuncion.setVisible(true);
        }
        else{
            
            dlgFuncion.setVisible(false);
            dlgFuncion.setA(0);
            dlgFuncion.setB(128);
            dlgFuncion.setC(255);
            deslizador_a.setValue(0);
            deslizador_b.setValue(128);
            deslizador_c.setValue(255);
            imgCopia=null;
        }
    }//GEN-LAST:event_boton_deslizadoresActionPerformed

    private void deslizador_aStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_aStateChanged
        // TODO add your handling code here: 
        dlgFuncion.setA(deslizador_a.getValue());
        aplicardeslizador(deslizador_a.getValue(),deslizador_b.getValue(),deslizador_c.getValue());
    }//GEN-LAST:event_deslizador_aStateChanged

    private void deslizador_bStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_bStateChanged
        // TODO add your handling code here:
        dlgFuncion.setB(deslizador_b.getValue());
        aplicardeslizador(deslizador_a.getValue(),deslizador_b.getValue(),deslizador_c.getValue());

    }//GEN-LAST:event_deslizador_bStateChanged

    private void deslizador_cStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_cStateChanged
        // TODO add your handling code here:
        dlgFuncion.setC(deslizador_c.getValue());
        aplicardeslizador(deslizador_a.getValue(),deslizador_b.getValue(),deslizador_c.getValue());
    }//GEN-LAST:event_deslizador_cStateChanged

    private void boton_invertirocuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_invertirocuroActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if(!oscuro_invertido){
                imgCopia = copiarImagen(vi.getLienzo2D().getImage());
                aplicardeslizador(255, 128, 255);
                oscuro_invertido = true;
            }
            else{
                vi.getLienzo2D().setImage(copiarImagen(imgCopia));     
                vi.getLienzo2D().repaint();
                oscuro_invertido = false;
            }   
        }
            
    }//GEN-LAST:event_boton_invertirocuroActionPerformed

    private void boton_tintadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tintadoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                TintOp tintado = new TintOp(Color.red, 0.5f);
                tintado.filter(img, img);
            }
        }
                   
    }//GEN-LAST:event_boton_tintadoActionPerformed

    private void boton_sepiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sepiaActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null) {
                SepiaOp sepia = new SepiaOp();
                sepia.filter(img, img);
            }
        }
    }//GEN-LAST:event_boton_sepiaActionPerformed

    private void deslizador_posterizacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_posterizacionStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgCopia != null) { 
            try {
                PosterizarOp posop = new PosterizarOp(this.deslizador_posterizacion.getValue());
                BufferedImage imgdest = posop.filter(imgCopia, null);
                vi.getLienzo2D().setImage(imgdest);
                vi.getLienzo2D().repaint();
            } catch (IllegalArgumentException e) {
                System.err.println(e.getLocalizedMessage());
            }    
        }
        
    }//GEN-LAST:event_deslizador_posterizacionStateChanged

    private void deslizador_posterizacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_posterizacionFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_posterizacionFocusGained

    private void deslizador_posterizacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_posterizacionFocusLost
        // TODO add your handling code here:
        imgFuente = null;
        this.deslizador_posterizacion.setValue(10);
    }//GEN-LAST:event_deslizador_posterizacionFocusLost

    private void boton_filtrorojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_filtrorojoActionPerformed
        // TODO add your handling code here:
        int umbral = 10;
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null ) { 
            BufferedImage img = vi.getLienzo2D().getImage();
            try {
                RojoOp rojoop = new RojoOp(umbral);
                BufferedImage imgdest = rojoop.filter(img, null);
                vi.getLienzo2D().setImage(imgdest);
                vi.getLienzo2D().repaint();
            } catch (IllegalArgumentException e) {
                System.err.println(e.getLocalizedMessage());
            }    
        }
    }//GEN-LAST:event_boton_filtrorojoActionPerformed

    private void boton_tonocolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tonocolorActionPerformed
        // TODO add your handling code here:
        Lienzo2D lienzo2D1 = getSelectedLienzo();
        if (boton_tonocolor.isSelected()) {
            VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null) {
                imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            }
        } 
        else {
            deslizador_desplazamiento.setValue(180);
            deslizador_umbral.setValue(180);
            VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null && imgCopia != null) {
                vi.getLienzo2D().setImage(copiarImagen(imgCopia));
                vi.getLienzo2D().repaint();
            }
        }
    }//GEN-LAST:event_boton_tonocolorActionPerformed

    private void deslizador_desplazamientoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_desplazamientoStateChanged
        // TODO add your handling code here:
        if(boton_tonocolor.isSelected()){
            Lienzo2D lienzo2D1 = getSelectedLienzo();
            aplicarTonoColorOp(deslizador_umbral.getValue(),lienzo2D1.getColor(),deslizador_desplazamiento.getValue());
        }
    }//GEN-LAST:event_deslizador_desplazamientoStateChanged

    private void deslizador_umbralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_umbralStateChanged
        // TODO add your handling code here:
        if(boton_tonocolor.isSelected()){
            Lienzo2D lienzo2D1 = getSelectedLienzo();
            aplicarTonoColorOp(deslizador_umbral.getValue(),lienzo2D1.getColor(),deslizador_desplazamiento.getValue());
        }
        
    }//GEN-LAST:event_deslizador_umbralStateChanged

    private void deslizador_tintadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_tintadoStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgCopia != null) {
            
            TintOp tintado = new TintOp(this.boton_color.getBackground(), this.deslizador_tintado.getValue()/100.0f);
            BufferedImage imgdest = tintado.filter(imgCopia, null);
            vi.getLienzo2D().setImage(imgdest);
            vi.getLienzo2D().repaint();
            
        }
    }//GEN-LAST:event_deslizador_tintadoStateChanged

    private void deslizador_tintadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_tintadoFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_tintadoFocusGained

    private void deslizador_tintadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_tintadoFocusLost
        // TODO add your handling code here:
        imgCopia = null;
        this.deslizador_tintado.setValue(1);
    }//GEN-LAST:event_deslizador_tintadoFocusLost

    private void deslizador_rojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_rojoStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgCopia != null) { 
            try {
                RojoOp rojoop = new RojoOp(this.deslizador_rojo.getValue());
                BufferedImage imgdest = rojoop.filter(imgCopia, null);
                vi.getLienzo2D().setImage(imgdest);
                vi.getLienzo2D().repaint();
            } catch (IllegalArgumentException e) {
                System.err.println(e.getLocalizedMessage());
            }    
        }
    }//GEN-LAST:event_deslizador_rojoStateChanged

    private void deslizador_rojoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_rojoFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_rojoFocusGained

    private void deslizador_rojoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_rojoFocusLost
        // TODO add your handling code here:
        imgCopia = null;
        this.deslizador_rojo.setValue(2);
    }//GEN-LAST:event_deslizador_rojoFocusLost

    private void deslizador_oscurecerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizador_oscurecerStateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null && imgCopia != null) { 
            try {
                OscurecerOp oscop = new OscurecerOp(this.deslizador_oscurecer.getValue()/100.0f);
                BufferedImage imgdest = oscop.filter(imgCopia, null);
                vi.getLienzo2D().setImage(imgdest);
                vi.getLienzo2D().repaint();
            } catch (IllegalArgumentException e) {
                System.err.println(e.getLocalizedMessage());
            }    
        }
    }//GEN-LAST:event_deslizador_oscurecerStateChanged

    private void deslizador_desplazamientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_desplazamientoFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deslizador_desplazamientoFocusGained

    private void deslizador_desplazamientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_desplazamientoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deslizador_desplazamientoFocusLost

    private void deslizador_oscurecerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_oscurecerFocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)(escritorio.getSelectedFrame());
        if(vi!=null){
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
        }
    }//GEN-LAST:event_deslizador_oscurecerFocusGained

    private void deslizador_oscurecerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deslizador_oscurecerFocusLost
        // TODO add your handling code here:
        imgCopia = null;
        this.deslizador_oscurecer.setValue(100);
    }//GEN-LAST:event_deslizador_oscurecerFocusLost

    private void boton_negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_negativoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            byte funcionT[] = new byte[256];
            for (int x = 0; x < 256; x++) {
                funcionT[x] = (byte) (255 - x); // Negativo
            }
            LookupTable tabla = new ByteLookupTable(0, funcionT);
            aplicarLookup(tabla);
        }
    }//GEN-LAST:event_boton_negativoActionPerformed

    private void boton_duplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_duplicarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            imgCopia = copiarImagen(vi.getLienzo2D().getImage());
            VentanaInterna viNueva = new VentanaInterna();
            viNueva.getLienzo2D().setImage(imgCopia);
            escritorio.add(viNueva);
            viNueva.setVisible(true);
        }
    }//GEN-LAST:event_boton_duplicarActionPerformed

    private void boton_realceOscurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_realceOscurosActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if(boton_realceOscuros.isSelected()){

                    imgCopia = copiarImagen(vi.getLienzo2D().getImage());
                    byte[] funcionT = new byte[256];

                    for (int i = 0; i < 256; i++) {
                        if (i < 128) {
                            // Aclara las sombras
                            funcionT[i] = (byte) (i + (128 - i) / 2);
                        } else {
                            // Mantiene luces igual
                            funcionT[i] = (byte) i;
                        }
                    }

                    LookupTable tabla = new ByteLookupTable(0, funcionT);
                    aplicarLookup(tabla);
                }
            else{
                vi.getLienzo2D().setImage(copiarImagen(imgCopia));     
                vi.getLienzo2D().repaint();
                
            }
        }
    }//GEN-LAST:event_boton_realceOscurosActionPerformed

    
    private void menu_audioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_audioActionPerformed
        // TODO add your handling code here:
       abrir();
        
    }//GEN-LAST:event_menu_audioActionPerformed

    /**
     * Función para abrir una nueva ventana interna.
     */
    private void nuevo(){
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage image;
        image = new BufferedImage(300,300,BufferedImage.TYPE_INT_RGB);
        
        Graphics2D g2d = image.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, image.getWidth(), image.getHeight());
        g2d.dispose();
        
        vi.getLienzo2D().setImage(image);
        
        //aplicarBotonesVentana();
        //reiniciarBotones();
        
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
         estado.setText(vi.getLienzo2D().getEstado());
        
        File f = new File(getClass().getResource("/sonidos/fijar.wav").getFile());
        vi.getLienzo2D().setSonidoFijar(f);
        f = new File(getClass().getResource("/sonidos/eliminar.wav").getFile());
        vi.getLienzo2D().setSonidoEliminar(f);
    }
    /**
     * Función para abrir una nueva imagen o audio.
     */
    private void abrir(){
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            try{
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo2D().setImage(img);
                this.escritorio.add(vi);
                vi.setTitle(f.getName());
                vi.setVisible(true);
                
                //aplicarBotonesVentana();
                //reiniciarBotones();
                
                File file = new File(getClass().getResource("/sonidos/fijar.wav").getFile());
                vi.getLienzo2D().setSonidoFijar(file);
                file = new File(getClass().getResource("/sonidos/eliminar.wav").getFile());
                vi.getLienzo2D().setSonidoEliminar(file);
            }catch(Exception ex){
                System.err.println("Error al leer la imagen");
            }
            
        }
    }
    
    private void aplicarTonoColorOp(int umbral,Color color, int desplazamiento){
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
            if (vi != null && imgCopia!=null) {
                try {
                    TonoColorOp top = new TonoColorOp(umbral, color, desplazamiento);
                    BufferedImage imgdest = top.filter(imgCopia, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
    }
  
    
    private void aplicarAffineTransform(AffineTransform at){
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            
            if (img != null) {
                try {
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }
    
    private BufferedImage copiarImagen(BufferedImage original) {
        ColorModel cm = original.getColorModel();
        WritableRaster raster = original.copyData(null);
        boolean alfaPre = original.isAlphaPremultiplied();
        BufferedImage copia = new BufferedImage(cm, raster, alfaPre, null);
        return copia;
    }

    
    private LookupTable funcionABC(int a,int b,int c){
        byte[] tabla = new byte[256];
        double K = 1.0;

        
        for(int x=0; x<256; x++){
            double y;
            if(x<128){
                y=(((b-a)*x)/128)+a;
            }
            else{
                y=(((c-b)*(x-128))/127)+b;
            }
            y=K*y;
            if (y < 0) {
                y = 0;
            } else if (y > 255) {
                y = 255;
            }
            tabla[x]=(byte)y;
        }
        return new ByteLookupTable(0,tabla);
    }
    
    private void aplicardeslizador(int a,int b,int c){
        LookupTable tabla = funcionABC(a,b,c);
        aplicarLookup(tabla);
    }
    
    private void aplicarLookup(LookupTable tabla){
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage();
            if (img != null && imgCopia!=null) {
                try {
                    LookupOp lop = new LookupOp(tabla, null);
                    lop.filter(imgCopia, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }
    
    //Función S para el contraste en lookup
    public static LookupTable sFuction(double m, double e){
        double Max = (1.0 / (1.0 + Math.pow(m / 255.0, e)));
        double K = 255.0 / Max;
        byte lt[] = new byte[256];
        lt[0] = 0;
        for (int l = 1; l < 256; l++) {
            lt[l] = (byte) (K * (1.0 / (1.0 + Math.pow(m / (float) l, e))));
        }
        ByteLookupTable slt = new ByteLookupTable(0, lt);
        return slt;
    }
    
    
    private BufferedImage getImageBand(BufferedImage img, int banda) {
        //Creamos el modelo de color de la nueva imagen basado en un espcio de color GRAY
        ColorSpace cs = ColorSpace.getInstance(ColorSpace.CS_GRAY);
        ComponentColorModel cm = new ComponentColorModel(cs, false, false,
                                                        Transparency.OPAQUE,
                                                        DataBuffer.TYPE_BYTE);
        //Creamos el nuevo raster a partir del raster de la imagen original
        int vband[] = {banda};
        WritableRaster bRaster = (WritableRaster) img.getRaster().createWritableChild(0, 0, img.getWidth(), img.getHeight(), 0, 0, vband);
        //Creamos una nueva imagen que contiene como raster el correspondiente a la banda
        return new BufferedImage(cm, bRaster, false, null);
    }
    
    private Kernel getKernel(int seleccion){
        Kernel k = null;
            
            switch(seleccion){
                case 0:
                    float filtro[] = KernelProducer.MASCARA_MEDIA_3x3;
                    k = new Kernel(3, 3, filtro);
                    /*int size = 5;
                    float[] filtro = new float[size * size];
                    float value = 1.0f / (size * size);

                    for (int i = 0; i < filtro.length; i++) {
                        filtro[i] = value;
                    }

                    Kernel k = new Kernel(size, size, filtro);*/

                break;
                case 1:
                    k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                 
                break;
                case 2:
                    k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);

                break;
                case 3:
                    k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                break;
                case 4:
                    k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                break;
                case 5:
                    k = KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);
                break;
            }
        return k;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BandCombineOp;
    private javax.swing.JMenuItem ColorConvertOp;
    private javax.swing.JMenuItem ConvolveOp;
    private javax.swing.JMenuItem RescaleOp;
    private javax.swing.JToggleButton boton_Elipse;
    private javax.swing.JToggleButton boton_Linea;
    private javax.swing.JToggleButton boton_Rectangulo;
    private javax.swing.JButton boton_abrir;
    private javax.swing.JButton boton_aclarar;
    private javax.swing.JToggleButton boton_alisado;
    private javax.swing.JButton boton_bandCombineOp;
    private javax.swing.JButton boton_color;
    private javax.swing.JButton boton_contraste1;
    private javax.swing.JToggleButton boton_curva;
    private javax.swing.JToggleButton boton_deslizadores;
    private javax.swing.JButton boton_duplicar;
    private javax.swing.JToggleButton boton_editar;
    private javax.swing.JToggleButton boton_eliminar;
    private javax.swing.JToggleButton boton_fijar;
    private javax.swing.JButton boton_filtrorojo;
    private javax.swing.JButton boton_girar180;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JButton boton_invertirocuro;
    private javax.swing.JButton boton_mas;
    private javax.swing.JButton boton_menos;
    private javax.swing.JToggleButton boton_negativo;
    private javax.swing.JButton boton_nuevo;
    private javax.swing.JButton boton_oscurecer;
    private javax.swing.JToggleButton boton_realceOscuros;
    private javax.swing.JToggleButton boton_relleno;
    private javax.swing.JButton boton_sepia;
    private javax.swing.JButton boton_showBandas;
    private javax.swing.JButton boton_tintado;
    private javax.swing.JToggleButton boton_tonocolor;
    private javax.swing.JToggleButton boton_transparencia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSlider deslizador_a;
    private javax.swing.JSlider deslizador_b;
    private javax.swing.JSlider deslizador_c;
    private javax.swing.JSlider deslizador_contraste;
    private javax.swing.JSlider deslizador_desplazamiento;
    private javax.swing.JSlider deslizador_emborronamiento;
    private javax.swing.JSlider deslizador_grosor;
    private javax.swing.JSlider deslizador_iluminacion;
    private javax.swing.JSlider deslizador_oscurecer;
    private javax.swing.JSlider deslizador_perfilado;
    private javax.swing.JSlider deslizador_posterizacion;
    private javax.swing.JSlider deslizador_rojo;
    private javax.swing.JSlider deslizador_tintado;
    private javax.swing.JSlider deslizador_umbral;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel estado;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JMenuItem menu_audio;
    private javax.swing.JComboBox<String> menu_convolveOp;
    private javax.swing.JComboBox<String> seleccionEspaciosColor;
    // End of variables declaration//GEN-END:variables
}
